version: '3.8'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: ./packages/api-posts/Dockerfile
    container_name: fastapi-app
    ports:
      - "3100:3100"
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: wordline
      POSTGRES_PASSWORD: wordline
      POSTGRES_DB: wordline
    volumes:
      - ./api-posts/data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    external: true
    name: backend